#!/usr/bin/env php
<?php
require_once __DIR__ . "/vendor/autoload.php";

use Symfony\Component\Console\Application;

$application = new Application();

$assembler = new \App\Assembler\Assembler();
$application->add(new \App\Command\AssembleCommand($assembler));

$application->run();