#!/usr/bin/env php
<?php
/**
 * Arquivo principal, inicializa as dependências e roda o AssembleCommand.
 */
require_once __DIR__ . "/vendor/autoload.php";

define('APP_ROOT', __DIR__);

use Symfony\Component\Console\Application;

$application = new Application();

$assembler = new \App\Assembler\Assembler();
$command = new \App\Command\AssembleCommand($assembler);

$application->add($command);
$application->setDefaultCommand($command->getName(), true);
$application->run();
